name: aur
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'
  push:
  pull_request:
jobs:
  update:
    runs-on: ubuntu-latest
    container: golang:1.21-bullseye
    if: ${{ secrets.SSH_KEY != '' && secrets.SSH_KEY_PASSWORD != '' }}
    steps:
      - uses: actions/checkout@v4

      - run: go run cmd/aur-autoupdater/main.go
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KEY_PASSWORD: ${{ secrets.SSH_KEY_PASSWORD }}
          GH_TOKEN_FOR_AUR_AUTO_UPDATE: ${{ github.token }}
